name: Publish docs

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Generate docs
        run: npm run docs

      - name: Publish docs
        uses: wangyucode/sftp-upload-action@v1.4.8
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteDir: ${{ secrets.FTP_DIRECTORY }}
          dryRun: false
          localDir: ./styleguide